site_name: 2020_5BI_Team6

nav:
    - 'Project Charter': 'ProjectCharter.md'
    - 'Software Requirements Specification Plan': 'SRS.md'
    - 'Software Project Management Plan': 'SPMP.md'
    
    
theme:
    name: readthedocs

