site_name: 2020_5AI_Team1

nav:
    - 'Project Charter': 'ProjectCharter.md'
    - 'Software Requirements Specification Plan': 'SRS.md'
    - 'Software Project Management Plan': 'SPMP.md'
    - 'Buisness Model Canvas': 'BuisnessModelCanvas.pdf'
    - 'Model Canvas': 'ModelCanvas.pdf'
    
    
theme:
    name: readthedocs

